services:
  - type: web
    name: telegram-quiz-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python SF_testing_bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        fromGroup: null
